server:
  port: 8081

# database configuration
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservices
    username:
    password:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: false
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  application:
    name: DEPARTMENT-SERVICE
  zipkin:
    base-url: http://localhost:9411